# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Recruter')], default=1, max_length=120),
            preserve_default=False,
        ),
    ]
